kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
  namespace: helloapp-alimurat-dev
  labels:
    app: helloapp
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: helloapp
  template:
    metadata:
      labels:
        deployment: helloapp
    spec:
      containers:
        - name: helloapp
          image: image-registry.openshift-image-registry.svc:5000/helloapp-alimurat-dev/helloapp:0.0.6
          ports:
            - containerPort: 5000
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: helloapp
  namespace: helloapp-alimurat-dev
  labels:
    app: helloapp
    app.kubernetes.io/component: helloapp
    app.kubernetes.io/instance: helloapp
    app.kubernetes.io/part-of: helloapp-app
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: helloapp
